"""empty message

Revision ID: 08fc8963a21f
Revises: 1915e346971a
Create Date: 2018-12-15 17:28:03.202803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fc8963a21f'
down_revision = '1915e346971a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_email', table_name='customer')
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.drop_index('ix_customer_name', table_name='customer')
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.drop_index('ix_customer_phone', table_name='customer')
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.create_index('ix_customer_phone', 'customer', ['phone'], unique=1)
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.create_index('ix_customer_name', 'customer', ['name'], unique=1)
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.create_index('ix_customer_email', 'customer', ['email'], unique=1)
    # ### end Alembic commands ###
