"""empty message

Revision ID: 1b757f283fb6
Revises: 08fc8963a21f
Create Date: 2018-12-21 00:13:31.276031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b757f283fb6'
down_revision = '08fc8963a21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('preferredShippingAddress', sa.Integer(), nullable=True))
    op.alter_column('customer', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customer', 'name',
               existing_type=sa.VARCHAR(length=70),
               nullable=False)
    op.alter_column('customer', 'phone',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.drop_index('ix_customer_time_created', table_name='customer')
    op.create_foreign_key(None, 'customer', 'shippingaddress', ['preferredShippingAddress'], ['id'])
    op.alter_column('shippingaddress', 'address',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('shippingaddress', 'city',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('shippingaddress', 'customerID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shippingaddress', 'state',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('shippingaddress', 'zip',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('subscription', 'customerID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscription', 'itemID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscription', 'shippingAddressID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscription', 'startDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('subscription', 'stopDate',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'stopDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('subscription', 'startDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('subscription', 'shippingAddressID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscription', 'itemID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscription', 'customerID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shippingaddress', 'zip',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('shippingaddress', 'state',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('shippingaddress', 'customerID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shippingaddress', 'city',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('shippingaddress', 'address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_index('ix_customer_time_created', 'customer', ['time_created'], unique=False)
    op.alter_column('customer', 'phone',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('customer', 'name',
               existing_type=sa.VARCHAR(length=70),
               nullable=True)
    op.alter_column('customer', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('customer', 'preferredShippingAddress')
    # ### end Alembic commands ###
