"""empty message

Revision ID: f639840ba3f5
Revises: 4c616d578586
Create Date: 2018-12-31 16:37:08.119997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f639840ba3f5'
down_revision = '4c616d578586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('preferredShippingAddress', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer', 'shippingaddress', ['preferredShippingAddress'], ['id'])
    op.add_column('shippingaddress', sa.Column('customerID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shippingaddress', 'customer', ['customerID'], ['id'])
    op.add_column('subscription', sa.Column('customerID', sa.Integer(), nullable=False))
    op.add_column('subscription', sa.Column('itemID', sa.Integer(), nullable=False))
    op.add_column('subscription', sa.Column('shippingAddressID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subscription', 'item', ['itemID'], ['id'])
    op.create_foreign_key(None, 'subscription', 'shippingaddress', ['shippingAddressID'], ['id'])
    op.create_foreign_key(None, 'subscription', 'customer', ['customerID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'shippingAddressID')
    op.drop_column('subscription', 'itemID')
    op.drop_column('subscription', 'customerID')
    op.drop_constraint(None, 'shippingaddress', type_='foreignkey')
    op.drop_column('shippingaddress', 'customerID')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'preferredShippingAddress')
    # ### end Alembic commands ###
